name: CI and CD

on:
  pull_request:
    branches:
      - develop

jobs:

  checkout-and-merge:
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.merge.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge to develop
        id: merge
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions"
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git fetch --all
          git switch develop
          git pull origin develop
          git switch ${{ github.event.pull_request.head.ref }}
          git rebase develop
          echo "success=true" >> $GITHUB_OUTPUT

  lint:
    needs: checkout-and-merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Lint checks
        run: ./gradlew ktlintCheck

  ui-test:
    needs: checkout-and-merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 29
            script: ./gradlew connectedCheck

  kover-test:
    needs: checkout-and-merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Unit Tests
        run: ./gradlew koverVerify

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            **/build/reports/kover/html/